### PR TITLE
#489 - Refactor work package backend

### LINKED ISSUE #489: Backend Refactoring - Work Packages
### Description

Refactor everything work package related

### Proposed Solution

1. separate each controller function into services and turn each into a class (see risk controller and risk service)
2. change all error calls to use the new custom exceptions (see error utils file and risk services to know what to throw)
3. move the query args to its own file (see risk query args file)
4. move the transformer to its own file (see risk transformer file)
5. update any existing tests to test the service function instead of using supertest and stuff (see risk test file)
6. update any testing types to use the prisma type and shared type for clarity (see risk test data file)
7. if any of the routes are using userId, delete it and use the auth userId instead (see editRisk controller)

### Info

see this epic and the attached pr for examples: https://github.com/Northeastern-Electric-Racing/FinishLine/issues/484

(pr: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/446)

### PR DESCRIPTION
**Pull request by jonathan-chen10**
## Changes

1. separate each controller function into services and turn each into a class
2. change all error calls to use the new custom exceptions
3. move WP query args to its own file
4. move WP transformer to its own file
5. update any existing WP tests to test the service function instead of using supertest and stuff
6. move WP test inputs to main test file, test data includes a WP for a CR test

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #489

### CODE REVIEW

File: src/backend/src/controllers/work-packages.controllers.ts [hunk 1]
```diff
@@ -1,425 +1,92 @@
...
-      userId,
-      wbsElementId!
-    );
-    if (projectManagerChangeJson) {
-      changes.push(projectManagerChangeJson);
+  // Create a work package with the given details
+  static async createWorkPackage(req: Request, res: Response, next: NextFunction) {
+    try {
+      const { body } = req;
+      const { projectWbsNum, name, crId, userId, startDate, duration, dependencies, expectedActivities, deliverables } =
```
Comment (anthonybernardi) [inline src/backend/src/controllers/work-packages.controllers.ts:35]: you can pull this all out in one line now doing `const { ... } = req.body`

File: src/backend/src/controllers/work-packages.controllers.ts [hunk 2]
```diff
@@ -1,425 +1,92 @@
...
-      crId,
-      userId,
-      wbsElementId!
-    );
-    if (projectLeadChangeJson) {
-      changes.push(projectLeadChangeJson);
+  // Edit a work package to the given specifications
+  static async editWorkPackage(req: Request, res: Response, next: NextFunction) {
+    try {
+      const { body } = req;
```
Comment (anthonybernardi) [inline src/backend/src/controllers/work-packages.controllers.ts:58]: same thign

File: src/backend/src/prisma-query-args/work-packages.query-args.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import { Prisma } from '@prisma/client';
+import { descBulletArgs } from '../utils/description-bullets.utils';
+
+const wpQueryArgs = Prisma.validator<Prisma.Work_PackageArgs>()({
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/work-packages.query-args.ts:4]: `workPackageQueryArgs` for clarity

File: src/backend/tests/work-packages.test.ts [hunk 4]
```diff
@@ -1,14 +1,16 @@
...
-import { createWorkPackagePayload } from './test-data/work-packages.test-data';
 import { changeBatmobile, unreviewedCr } from './test-data/change-requests.test-data';
 import { getChangeRequestReviewState } from '../src/utils/projects.utils';
 import { calculateWorkPackageProgress } from '../src/utils/work-packages.utils';
+import { AccessDeniedException, HttpException, NotFoundException } from '../src/utils/errors.utils';
+import WorkPackageService from '../src/services/work-packages.services';
+import { WbsNumber } from 'shared';
+import { WBS_Element, WBS_Element_Status } from '@prisma/client';
 
 const app = express();
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:15]: we can get rid of this now and test service methods instead of the controllers

File: src/backend/tests/work-packages.test.ts [hunk 5]
```diff
@@ -18,121 +20,169 @@ jest.mock('../src/utils/projects.utils');
 const mockGetChangeRequestReviewState = getChangeRequestReviewState as jest.Mock<Promise<boolean | null>>;
 
 describe('Work Packages', () => {
+  /* WORK PACKAGE PAYLOAD */
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:23]: i think someting like `SERVICE FUNCTION INPUT ARGUMENTS` makes more sense

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
awesome work! basically no comments, great attention to detail.

only thing is i merged in a test pr that created some conflicts so you'll have to fix those too

**Review by anthonybernardi — APPROVED** [review]
amazing
