### PR TITLE
#956 - Remove Task List Loading Indicator With No Team

### LINKED ISSUE #956: Tasks stuck on loading screen when project is not assigned to a team
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop

### Version(s)

production (main), develop

### Observed Behavior

Tasks will have three loading indicators when the project is not on a team

### Expected Behavior

Tasks should just be empty if the project is not on a team

### Steps to Reproduce

1. go to genesis project
2. look at task list
3. or create a new project and dont assign a team

### Screenshots (as needed)

Screen Shot 2023-03-02 at 12 16 27 PM

### PR DESCRIPTION
**Pull request by jonathan-chen10**
## Changes

Instead of displaying loading symbol if a project has no team, display helpful text message instead.

New Task button also disabled if no team. Task edit permission is controlled *per task* now.

Refactor task list test data using mock hooks, and change task list props to pass the whole project. Plus some free task test data I didn't get to use.

## Notes

I chose to display text instead of nothing to make it more user-friendly.

Did not do similar changes for `!auth.user` (will that ever happen?) or `AssigneeEdit` component (does this ever get displayed?)

## Test Cases

- New Task Button
  - Disabled if no team
  - (manual) Assigning a project to a team will instantly refresh component to show table and enable button
- Displaying "no team" message
  - Renders if no associated team
  - No render if there is a team

Manually checking edit permission is controlled per task:
1. Use admin tools to demote Joe Shmoe to guest.
2. Log in as Joe Shmoe
3. Project 1.1.0 > tasks In Progress
4. "Decorate Impact Attenuator" should be enabled
5. "Meet with the Department of Transportation" should be disabled (both in move/delete task menu and in the edit modal)

## Screenshots

Screen Shot 2023-03-07 at 9 54 06 PM
Screen Shot 2023-03-07 at 9 54 52 PM
Screen Shot 2023-03-07 at 9 54 13 PM

## To Do

_Any remaining things that need to get done_

- [x] Disable New Task button if there is no team. (Is there some way to couple all this together?)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #956

### CODE REVIEW

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx [hunk 1]
```diff
@@ -36,10 +36,12 @@ const TaskList = ({ tasks, currentWbsNumber, defaultClosed, team, hasTaskPermiss
     setValue(newValue);
   };
 
+  const disableAddTask: boolean = auth.user?.role === 'GUEST' || !team;
```
Comment (Peyton-McKee) [inline src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx:39]: this is incorrect logic... there was a giant thread about permissions in software product requests I think, Ill slack you if you cant find the exact logic. Its pretty similar to the edit task permissions in the task modal, but its not the exact same

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx [hunk 2]
```diff
@@ -144,7 +144,11 @@ const TaskListTabPanel = (props: TaskListTabPanelProps) => {
     [assignees]
   );
 
-  if (isLoading || assigneeIsLoading || !auth.user || !team) return <LoadingIndicator />;
+  const failMessageStyle: SxProps = { py: '25px', textAlign: 'center' };
+
+  if (isLoading || assigneeIsLoading || !auth.user) return <LoadingIndicator />;
+  if (!team)
+    return <>{value === index && <Typography sx={failMessageStyle}>No team assigned to this project!</Typography>}</>;
```
Comment (Peyton-McKee) [inline src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx:151]: I think this syntax is confusing, lets just make a component called like NoTeamErrorMessage and then return that if theres no team maybe

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
Looks great! I dont really know anything about frontend tests. Although Anthony always tells me he has a super easy way of mocking stuff in the frontend (this might be it i honestly have no idea) Also for the component thing its essentially a function thats capitalized so that you can call it like a component (Reid taught me that from his coop or something)

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx (hunk 2 above)
Comment (anthonybernardi) [inline src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskListTabPanel.tsx:151]: id say just put the sx inline since it's only getting used once

also I think a more informational message like "A project can only have tasks if it is assigned to a team"

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx (hunk 1 above)
Comment (anthonybernardi) [reply src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx:39]: ^

File: src/frontend/src/tests/pages/ProjectDetailPage/TaskList.test.tsx [hunk 3]
```diff
@@ -31,10 +32,22 @@ const mockAuthHook = (user = exampleAdminUser) => {
 };
 
 jest.mock('../../../hooks/tasks.hooks');
+const mockedCreateTask = useCreateTask as jest.Mock<UseMutationResult>;
+const mockCreateTaskHook = (isLoading: boolean, isError: boolean, error?: Error) => {
```
Comment (anthonybernardi) [inline src/frontend/src/tests/pages/ProjectDetailPage/TaskList.test.tsx:36]: so look at mock-hooks.ts in the test-support folder and then see how i use stuff like mockEditProjectReturnValue in tests

imo it's easier because it cuts way down on # of lines

**Review by anthonybernardi — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx [hunk 4]
```diff
@@ -134,7 +134,7 @@ const ProjectViewContainer: React.FC<ProjectViewContainerProps> = ({ proj, enter
     </div>
   );
 
-  const hasTaskPermissions =
+  const createTaskPermissions =
```
Comment (RChandler234) [inline src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx:137]: why the name change here

**Review by RChandler234 — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx (hunk 4 above)
Comment (RChandler234) [reply src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx:137]: or I guess more so if we change the name here why don't we change the prop we're passing it into as well

Comment (jonathan-chen10) [reply src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx:137]: sure, i can separate create and edit permissions in every component

**Review by RChandler234 — DISMISSED** [review]
Looks good! Sorry for the delay on reviewing.
