### PR TITLE
#490 cr backend refactoring

### LINKED ISSUE #490: Backend Refactoring - Change Requests
### Description

Refactor everything change request related

### Proposed Solution

1. separate each controller function into services and turn each into a class (see risk controller and risk service)
2. change all error calls to use the new custom exceptions (see error utils file and risk services to know what to throw)
3. move the query args to its own file (see risk query args file)
4. move the transformer to its own file (see risk transformer file)
5. update any existing tests to test the service function instead of using supertest and stuff (see risk test file)
6. update any testing types to use the prisma type and shared type for clarity (see risk test data file)
7. if any of the routes are using userId, delete it and use the auth userId instead (see editRisk controller)

### Info

see this epic and the attached pr for examples: https://github.com/Northeastern-Electric-Racing/FinishLine/issues/484

(pr: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/446)

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

Refactored the entire cr backend endpoints and utils and tests

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #490  (issue #)

### CODE REVIEW

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 1]
```diff
@@ -1,509 +1,104 @@
...
+import ChangeRequestService from '../services/change-request.services';
+
+export default class CRController {
+  // Fetch the specific change request by its integer ID
+  static async getChangeRequestByID(req: Request, res: Response, next: NextFunction) {
+    try {
+      const crId: number = parseInt(req.params.crId);
+      const cr = await ChangeRequestService.getChangeRequestByID(crId);
+      return res.status(200).json(cr);
+    } catch (error: unknown) {
```
Comment (Ari-S-123) [inline src/backend/src/controllers/change-requests.controllers.ts:11]: Is there anything better than `unknown` that can be used instead?

Comment (Peyton-McKee) [reply src/backend/src/controllers/change-requests.controllers.ts:11]: I just used unknown cause thats what is used in the risks file

Comment (anthonybernardi) [reply src/backend/src/controllers/change-requests.controllers.ts:11]: no this is how typescript works unfortunately

Comment (anthonybernardi) [reply src/backend/src/controllers/change-requests.controllers.ts:11]: the error handler checks what type of error it is though

File: src/backend/src/prisma-query-args/change-request.query-args.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import { Prisma } from '@prisma/client';
+import scopeCRArgs from './scope-change-request.query-args';
+
+const changeRequestRelationArgs = Prisma.validator<Prisma.Change_RequestArgs>()({
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/change-request.query-args.ts:4]: lets go with `changeRequestQueryArgs`

File: src/backend/src/prisma-query-args/proposed-solutions.query-args.ts [hunk 3]
```diff
@@ -0,0 +1,8 @@
+import { Prisma } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/proposed-solutions.query-args.ts:1]: new line after

File: src/backend/src/prisma-query-args/proposed-solutions.query-args.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+const proposedSolutionArgs = Prisma.validator<Prisma.Proposed_SolutionArgs>()({
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/proposed-solutions.query-args.ts:2]: `proposedSolutionQueryArgs`

File: src/backend/src/prisma-query-args/change-request.query-args.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
+import { Prisma } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/change-request.query-args.ts:1]: file name should be plural (change-requests.query-args.ts)

File: src/backend/src/prisma-query-args/scope-change-request.query-args.ts [hunk 6]
```diff
@@ -0,0 +1,11 @@
+import { Prisma } from '@prisma/client';
+import proposedSolutionArgs from './proposed-solutions.query-args';
+
+const scopeCRArgs = Prisma.validator<Prisma.Scope_CRArgs>()({
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/scope-change-request.query-args.ts:4]: `scopeChangeRequestQueryArgs`

File: src/backend/src/prisma-query-args/scope-change-request.query-args.ts [hunk 7]
```diff
@@ -0,0 +1,11 @@
+import { Prisma } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/src/prisma-query-args/scope-change-request.query-args.ts:1]: plural file name

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 8]
```diff
@@ -1,509 +1,104 @@
...
-                create: changes[0]
-              }
-            }
-          }
-        }
-      });
+import { Request, Response, NextFunction } from 'express';
+import ChangeRequestService from '../services/change-request.services';
+
+export default class CRController {
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:4]: `ChangeRequestsController`

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 9]
```diff
@@ -1,509 +1,104 @@
...
-          wbsElement: {
-            update: {
-              changes: {
-                create: changes[0]
-              }
-            }
-          }
-        }
-      });
+import { Request, Response, NextFunction } from 'express';
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:1]: new line between each static function

also you can take out all the one line comments, it's the service class that should be heavily documented

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 10]
```diff
@@ -1,509 +1,104 @@
...
-    if (shouldChangeStatus) {
-      changesList.push({
-        changeRequestId: crId,
-        implementerId: reviewerId,
-        detail: buildChangeDetail('status', wbsElement.status, WBS_Element_Status.COMPLETE)
-      });
+  // handle reviewing of change requests
+  static async reviewChangeRequest(req: Request, res: Response, next: NextFunction) {
+    try {
+      const { body } = req;
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:26]: for all of these functions it should instead be:

`const { reviewerId, crId, reviewNotes, accepted, psId } = req.body;`

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 11]
```diff
@@ -1,509 +1,104 @@
...
-          'Start Date',
-          wbsElement.workPackage?.startDate.toLocaleDateString() || 'null',
-          actCr.startDate.toLocaleDateString()
-        )
-      });
+  static async createActivationChangeRequest(req: Request, res: Response, next: NextFunction) {
+    try {
+      const { body } = req;
+      const id = ChangeRequestService.createActivationChangeRequest(
+        body.submitterId,
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:38]: declare them all first in a separate line

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 12]
```diff
@@ -1,509 +1,104 @@
...
-      wbsNumber: {
-        carNumber: body.wbsNum.carNumber,
-        projectNumber: body.wbsNum.projectNumber,
-        workPackageNumber: body.wbsNum.workPackageNumber
-      }
+  static async createStageGateChangeRequest(req: Request, res: Response, next: NextFunction) {
+    try {
+      const { body } = req;
+      const id = ChangeRequestService.createStageGateChangeRequest(
+        body.submitterId,
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:57]: this should be removed and replaced with a call to `getCurrentUser` from the utils file and same with any other function that is using the id of the user sending the request (see editRisk)

File: src/backend/src/transformers/change-request.transformer.ts [hunk 13]
```diff
@@ -0,0 +1,63 @@
+import { Prisma } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/src/transformers/change-request.transformer.ts:1]: plural file name

File: src/backend/src/transformers/proposed-solution.transformer.ts [hunk 14]
```diff
@@ -0,0 +1,21 @@
+import { Prisma } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/src/transformers/proposed-solution.transformer.ts:1]: plural file name

File: src/backend/src/services/change-request.services.ts [hunk 15]
```diff
@@ -0,0 +1,501 @@
...
+import prisma from '../prisma/prisma';
+import changeRequestRelationArgs from '../prisma-query-args/change-request.query-args';
+import { AccessDeniedException, HttpException, NotFoundException } from '../utils/errors.utils';
+import changeRequestTransformer from '../transformers/change-request.transformer';
+import { Role, CR_Type, WBS_Element_Status } from '@prisma/client';
+import { sendSlackChangeRequestNotification, sendSlackCRReviewedNotification } from '../utils/change-requests.utils';
+import { buildChangeDetail } from '../utils/utils';
+import { getUserFullName } from '../utils/users.utils';
+
+export default class ChangeRequestService {
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:11]: `ChangeRequestsService`

File: src/backend/src/services/change-request.services.ts [hunk 16]
```diff
@@ -0,0 +1,501 @@
...
+  static async getChangeRequestByID(crId: number): Promise<ChangeRequest> {
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:12]: each of these should have detailed jsdoc like in the risks service (type /** then press enter and it will set up the template for you)

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
getting real pedantic with this one so sorry in advance but tbh that's the point of refactoring. we want everything to be consistent to make this as easy to work on as possible for people

the reason i want plural file names for everything is because everything should follow our endpoint urls which is always /risks or /change-requests or whatever so the files should match that

File: src/backend/tests/change-requests.test.ts [hunk 17]
```diff
@@ -12,6 +11,8 @@ import {
 } from './test-data/change-requests.test-data';
 import { project1 } from './test-data/projects.test-data';
 import { CR_Type } from '@prisma/client';
+import ChangeRequestService from '../src/services/change-request.services';
+import { AccessDeniedException, HttpException, NotFoundException } from '../src/utils/errors.utils';
 
 const app = express();
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:17]: we shouldnt need the app anymore as we should now just be testing the service and not the controller

File: src/backend/tests/change-requests.test.ts [hunk 18]
```diff
@@ -24,39 +25,81 @@ describe('Change Requests', () => {
...
       jest.spyOn(prisma.user, 'findUnique').mockResolvedValueOnce(wonderwoman);
-      const response = await request(app)
-        .post('/review')
-        .send({ ...whipPayloadObject, accepted: false });
-      expect(response.body).toStrictEqual({ message: 'Access Denied' });
-      expect(response.status).toBe(403);
+
+      try {
+        await ChangeRequestService.reviewChangeRequest(
+          whipPayloadObject.reviewerId,
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:50]: now that we dont have the request bodys, we don't need payload objects at all and can just use variables

File: src/backend/tests/change-requests.test.ts [hunk 19]
```diff
@@ -24,39 +25,81 @@ describe('Change Requests', () => {
...
+          whipPayloadObject.crId,
+          whipPayloadObject.reviewNotes,
+          whipPayloadObject.accepted,
+          '1'
+        );
+      } catch (e) {
+        // eslint-disable-next-line jest/no-conditional-expect
+        expect(e).toBeInstanceOf(NotFoundException);
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:38]: instead of a try catch, you can do:
```
await expect(() =>
        ChangeRequestService.reviewChangeRequest(
          whipPayloadObject.reviewerId,
          whipPayloadObject.crId,
          whipPayloadObject.reviewNotes,
          whipPayloadObject.accepted,
          '1'
        )
      ).rejects.toThrow(new NotFoundException('User', 1));
```

File: src/backend/tests/change-requests.test.ts (hunk 18 above)
Comment (anthonybernardi) [reply src/backend/tests/change-requests.test.ts:50]: with stuff like this, try to see what you can abstract and declare outside of the tests so you're not rewriting tons of the same variables in the code over and over

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
another really important thing we need to do with these PRs is to refactor the test data. we should get rid of all payloads since we don't need them anymore.

Also all testing objects should be type annoted to be either from prisma or shared type (see risks test data for a good way to do this)

File: src/backend/tests/change-requests.test.ts (hunk 19 above)
Comment (Peyton-McKee) [reply src/backend/tests/change-requests.test.ts:38]: You have no idea how long I looked for something like that. I had .toThrow, I didn’t know you had to put .rejects first omg

File: src/backend/src/controllers/change-requests.controllers.ts [hunk 20]
```diff
@@ -1,512 +1,113 @@
...
-              }
-            }
-          }
-        }
-      });
+import { Request, Response, NextFunction } from 'express';
+import ChangeRequestsService from '../services/change-request.services';
+import { getCurrentUser } from '../utils/utils';
+
+export default class ChangeRequestController {
```
Comment (anthonybernardi) [inline src/backend/src/controllers/change-requests.controllers.ts:5]: plural

File: src/backend/src/services/change-request.services.ts [hunk 21]
```diff
@@ -0,0 +1,556 @@
+import { ChangeRequest } from 'shared';
+import prisma from '../prisma/prisma';
+import changeRequestRelationArgs from '../prisma-query-args/change-requests.query-args';
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:3]: should be called queryArgs

File: src/backend/src/services/change-request.services.ts [hunk 22]
```diff
@@ -0,0 +1,556 @@
...
+import { AccessDeniedException, HttpException, NotFoundException } from '../utils/errors.utils';
+import changeRequestTransformer from '../transformers/change-requests.transformer';
+import { Role, CR_Type, WBS_Element_Status, User } from '@prisma/client';
+import { sendSlackChangeRequestNotification, sendSlackCRReviewedNotification } from '../utils/change-requests.utils';
+import { buildChangeDetail } from '../utils/utils';
+import { getUserFullName } from '../utils/users.utils';
+
+export default class ChangeRequestsService {
+  /**
+   *
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:13]: each of these functions should have a description sentence on this line

File: src/backend/src/services/change-request.services.ts [hunk 23]
```diff
@@ -0,0 +1,556 @@
...
+
+    // If approving a scope CR
+    if (foundCR.scopeChangeRequest && accepted) {
+      // ensure a proposed solution is being approved and exists
+      if (!psId) throw new HttpException(400, 'No proposed solution selected for scope change request');
+      const foundPs = await prisma.proposed_Solution.findUnique({
+        where: { proposedSolutionId: psId }
+      });
+      if (!foundPs || foundPs.changeRequestId !== foundCR.scopeChangeRequest.scopeCrId)
+        throw new HttpException(404, `Proposed solution with id #${psId} not found for change request #${crId}`);
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:82]: this should be a not found exception

File: src/backend/src/services/change-request.services.ts [hunk 24]
```diff
@@ -0,0 +1,556 @@
...
+        where: { wbsElementId: foundCR.wbsElementId },
+        data: {
+          projectLeadId: actCr.projectLeadId,
+          projectManagerId: actCr.projectManagerId,
+          workPackage: { update: { startDate: actCr.startDate } },
+          status: WBS_Element_Status.ACTIVE
+        }
+      });
+    }
+    // send the creator of the cr a slack notification that their cr was reviewed
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:261]: line break for readability

File: src/backend/src/services/change-request.services.ts [hunk 25]
```diff
@@ -0,0 +1,556 @@
...
+    const creatorUserSettings = await prisma.user_Settings.findUnique({ where: { userId: foundCR.submitterId } });
+    if (creatorUserSettings && creatorUserSettings.slackId) {
+      await sendSlackCRReviewedNotification(creatorUserSettings.slackId, foundCR.crId);
+    }
+    // finally we can update change request
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:266]: linebreak

File: src/backend/src/services/change-request.services.ts [hunk 26]
```diff
@@ -0,0 +1,556 @@
...
+      where: { crId },
+      data: {
+        reviewer: { connect: { userId: reviewer.userId } },
+        reviewNotes,
+        accepted,
+        dateReviewed: new Date()
+      },
+      include: { activationChangeRequest: true, wbsElement: { include: { workPackage: true } } }
+    });
+    // TODO: handle errors
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:277]: delete this comment and linebreak

File: src/backend/src/services/change-request.services.ts [hunk 27]
```diff
@@ -0,0 +1,556 @@
...
+    const team = createdCR.wbsElement.workPackage?.project.team;
+    if (team) {
+      const slackMsg =
+        `${submitter.firstName} ${submitter.lastName} wants to activate ${createdCR.wbsElement.name}` +
+        ` in ${createdCR.wbsElement.workPackage?.project.wbsElement.name}`;
+      await sendSlackChangeRequestNotification(team, slackMsg, createdCR.crId);
+    }
+
+    return createdCR.crId;
+  }
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:359]: linebreak after the function

File: src/backend/src/services/change-request.services.ts [hunk 28]
```diff
@@ -0,0 +1,556 @@
...
+   * @throws if user is not allowed to create crs, if wbs element does not exist, or if the cr type is not standard
+   */
+  static async createStandardChangeRequest(
+    submitter: User,
+    carNumber: number,
+    projectNumber: number,
+    workPackageNumber: number,
+    type: CR_Type,
+    what: string,
+    why: any,
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:452]: this shouldn't be `any`, you can look at the validation on teh route to see what values it should have

File: src/backend/src/services/change-request.services.ts [hunk 29]
```diff
@@ -0,0 +1,556 @@
...
+ * 
+ * @param submitter  The user creating the cr
+ * @param crId  the id of the change request
+ * @param budgetImpact  the impact on the budget
+ * @param description  the description of the proposed solution
+ * @param timelineImpact  the impact on the timeline
+ * @param scopeImpact  the impact on the scope
+ * @returns  the id of the created cr
+ * @throws if user is not allowed to create crs, if the change request is not found, or if the change request has already been reviewed
+ */
```
Comment (anthonybernardi) [inline src/backend/src/services/change-request.services.ts:518]: these comments are misaligned, run prettier on this file. why does your prettier keep getting turned off?

File: src/backend/tests/change-requests.test.ts [hunk 30]
```diff
@@ -1,149 +1,143 @@
...
-const app = express();
-app.use(express.json());
-app.use('/', changeRequestsRouter);
+import ChangeRequestsService from '../src/services/change-request.services';
+import { AccessDeniedException, HttpException, NotFoundException } from '../src/utils/errors.utils';
 
 describe('Change Requests', () => {
   afterEach(() => {
     jest.clearAllMocks();
   });
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:21]: linebreak after

File: src/backend/tests/change-requests.test.ts [hunk 31]
```diff
@@ -1,149 +1,143 @@
...
-    test('reviewer not found errors', async () => {
-      jest.spyOn(prisma.user, 'findUnique').mockResolvedValue(null);
-      const response = await request(app).post('/review').send(whipPayloadObject);
-
-      expect(response.body).toStrictEqual({ message: `User with id #${whipPayloadObject.reviewerId} not found` });
-      expect(response.status).toBe(404);
-      expect(prisma.user.findUnique).toHaveBeenCalledTimes(1);
-    });
-
+    const scopeCR = { ...redesignWhip, accepted: false, scopeChangeRequest: redesignWhipScopeCR };
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:23]: linebreak after

File: src/backend/tests/change-requests.test.ts [hunk 32]
```diff
@@ -1,149 +1,143 @@
...
     test('did not select proposed solution', async () => {
-      jest.spyOn(prisma.user, 'findUnique').mockResolvedValue(batman);
-      jest.spyOn(prisma.change_Request, 'findUnique').mockResolvedValueOnce({ ...redesignWhip, accepted: false });
-
-      const response = await request(app).post('/review').send(whipPayloadObject);
-
-      expect(response.body).toStrictEqual({ message: 'No proposed solution selected for scope change request' });
-      expect(response.status).toBe(400);
-      expect(prisma.user.findUnique).toHaveBeenCalledTimes(1);
+
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:75]: no line needed here

File: src/backend/tests/change-requests.test.ts [hunk 33]
```diff
@@ -1,149 +1,143 @@
...
-      const psId = 100;
-      const response = await request(app)
-        .post('/review')
-        .send({ ...whipPayloadObject, psId: '100' });
-      expect(response.status).toBe(404);
-      expect(response.body).toStrictEqual({
-        message: `Proposed solution with id #${psId} not found for change request #${redesignWhip.crId}`
-      });
-      expect(prisma.user.findUnique).toHaveBeenCalledTimes(1);
+
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:89]: delete

File: src/backend/tests/change-requests.test.ts [hunk 34]
```diff
@@ -1,149 +1,143 @@
...
+      jest.spyOn(prisma.change_Request, 'findUnique').mockResolvedValueOnce(scopeCR);
+
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:91]: delete but then new line after the jest spyon

File: src/backend/tests/change-requests.test.ts [hunk 35]
```diff
@@ -1,149 +1,143 @@
...
-      const response = await request(app)
-        .post('/review')
-        .send({ ...whipPayloadObject, psId: '1' });
-      expect(response.status).toBe(404);
-      expect(response.body).toStrictEqual({
-        message: `Work package project not found`
-      });
-      expect(prisma.user.findUnique).toHaveBeenCalledTimes(1);
+
+      await expect(() => ChangeRequestsService.reviewChangeRequest(superman, reviewChangeRequestParams.crId, reviewChangeRequestParams.reviewNotes, reviewChangeRequestParams.accepted, '1')).rejects.toThrow(new NotFoundException('Project', 100));
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:115]: this line is way too long, turn on prettier

File: src/backend/tests/change-requests.test.ts [hunk 36]
```diff
@@ -214,69 +207,86 @@ describe('Change Requests', () => {
...
+        ChangeRequestsService.reviewChangeRequest(
+          superman,
+          reviewChangeRequestParams.crId,
+          reviewChangeRequestParams.reviewNotes,
+          reviewChangeRequestParams.accepted,
+          '1'
+        )).rejects.toThrow(new HttpException(400, 'Work Package has unchecked deliverables'));
+      expect(prisma.change_Request.findUnique).toHaveBeenCalledTimes(1);
+    });
+    test('Stage Gate CR Succeeds', async () => {
```
Comment (anthonybernardi) [inline src/backend/tests/change-requests.test.ts:261]: newline

File: src/backend/tests/test-data/change-requests.test-data.ts [hunk 37]
```diff
@@ -1,27 +1,41 @@
-import { CR_Type, Scope_CR_Why_Type } from '@prisma/client';
```
Comment (anthonybernardi) [inline src/backend/tests/test-data/change-requests.test-data.ts:1]: this file has also not been prettier'd

File: src/backend/tests/test-data/change-requests.test-data.ts [hunk 38]
```diff
@@ -32,118 +46,120 @@ export const solutionToRedesignWhip = {
...
+  type: PrismaScopeCRWhyType.DESIGN,
   explain: 'because it looks better'
 };
-export const redesignWhipScopeCR = {
+export const redesignWhipScopeCR : PrismaScopeCR = {
   scopeCrId: 1,
   changeRequestId: 2,
   what: 'redesign whip',
-  why: redesignWhipWhy,
+  //why: redesignWhipWhy,
```
Comment (anthonybernardi) [inline src/backend/tests/test-data/change-requests.test-data.ts:59]: delete

File: src/backend/tests/test-data/change-requests.test-data.ts [hunk 39]
```diff
@@ -32,118 +46,120 @@ export const solutionToRedesignWhip = {
...
+    dateTimeChecked: new Date('10/10/2022'),
+    dateDeleted: null,
+    projectIdGoals: null,
+    projectIdFeatures: null,
+    projectIdOtherConstraints: null,
+    workPackageIdDeliverables: null,
+    detail: 'redesign whip',
+    workPackageIdExpectedActivities: 1
+  };
+export const whipDeliverables: PrismaDescriptionBullet =
```
Comment (anthonybernardi) [inline src/backend/tests/test-data/change-requests.test-data.ts:79]: need new lines between objects throuhgout the file

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
most of these comments are for readability. it may seem dumb but it's so important for a big codebase like this especially when we have tons of people working on it all the time

general guidelines are like functions or tests should have lines between them. linebreaks should be used to separate logical steps and not used to keep related lines together.

also if you have prettier on it will do most of this work for you
