### PR TITLE
#2244 - Finance Fixes - Deny own reimbursement request

### LINKED ISSUE #2244: Finance Fixes - Deny own reimbursement request
### Observed Behavior

Right now you need specific permissions to deny a reimbursement request

### Expected Behavior

We want users to be able to deny their own reimbursement requests, in case they made a mistake or something

### Steps to Reproduce

1. Make a reimbursement request with a user who does not have perms to deny
2. try and deny your own request
3. 

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by staysgt**
## Changes

User can now deny their own reimbursements requests, regardless of whether they are on the finance team. Updated both backend and frontend.

## Test Cases

- Regular deny reimbursement request still works
- Non finance user can deny their own reimbursement request

## Screenshots
Screenshot 2025-02-18 at 10 08 56 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2244

### CODE REVIEW

**Comment by kyanbarker** [comment]
Looks good! Do you think you could get a screenshot to show that the deny button appears for users' own reimbursement requests?

**Comment by staysgt** [comment]
@kb578432 added

**Review by vsp05 — DISMISSED** [review]
Great work, Sarah! Thank you sm for writing the test as well!

File: src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx [hunk 1]
```diff
@@ -462,7 +462,7 @@ const ReimbursementRequestDetailsView: React.FC<ReimbursementRequestDetailsViewP
       onClick: () => setShowDenyModal(true),
       icon: <CloseIcon />,
       disabled:
-        !user.isFinance ||
+        (!user.isFinance && user.userId !== reimbursementRequest.recipient.userId) ||
```
Comment (walker-sean) [inline src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx]: Interesting that we actually had this button disabled for non-finance admins, can  you add that check here?

**Review by walker-sean — CHANGES_REQUESTED** [review]

**Review by walker-sean — APPROVED** [review]
LGTM
