### PR TITLE
#1898 Fix Create CR Button

### LINKED ISSUE #1898: Auto Implementing CRs - Create Change Request from Work Package Edits
### Description

Blocked by #1894 but you can start on the form before it's done

when a person is in the edit form for a work package, there should be a button at the top of the page that says "Create Change Request From Changes" whenever they make any edits to the default values. Clicking this button should submit a scope CR to the backend with wbs proposed changes and work package proposed changes from the form inputs

This form should spit you out on the CR overview page  once submitted

### Proposed Solution

Just submit whatever is in the form, we'll worry about displaying the diff/ figuring out what to change in the change request page and review CR endpoint

epic #1892

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

Deleted separate route for creating a work package with a CR. Everything can be inferred by whether or not the button is pressed on the form. This makes the code much much cleaner and makes integrating it with projects and other wbs elements trivial to follow. 

## Screenshots

I tested it and it works. I assume the review scope cr change request hasnt been finished and thats why i cannot accept it without a proposed solution. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1898  (issue #)

### CODE REVIEW

File: src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx [hunk 1]
```diff
@@ -7,26 +7,28 @@ import ErrorPage from '../ErrorPage';
...
-import { WPFormType } from '../../utils/form';
 import { WorkPackageApiInputs } from '../../apis/work-packages.api';
 import { ObjectSchema } from 'yup';
+import { CreateStandardChangeRequestPayload } from '../../hooks/change-requests.hooks';
 
 interface WorkPackageFormProps {
   wbsNum: WbsNumber;
   exitActiveMode: () => void;
   crId?: string;
   mutateAsync: (data: WorkPackageApiInputs) => void;
```
Comment (RChandler234) [inline src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx:18]: Can u rename this one to be onFormSubmit (bad name) or smthn, since the other one u added is also technically a mutateAsync

File: src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx [hunk 2]
```diff
@@ -160,45 +187,25 @@ const WorkPackageFormView: React.FC<WorkPackageFormViewProps> = ({
...
-              title={
-                'This form will create a change request that when accepted will automatically create a new Work Package'
-              }
-              placement="right"
-            >
-              <HelpIcon style={{ fontSize: '1.5em', color: 'lightgray' }} />
-            </Tooltip>
-          )
-        }
+        title={`${wbsPipe(wbsElement.wbsNum)} - ${wbsElement.name}`}
```
Comment (RChandler234) [inline src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx:196]: Not at my laptop so apologies if u added this and I missed it, can u add this info bubble with tooltip somewhere that makes sense, I want ppl to be able to figure out how to use this form with no ambiguity with just the info on the page without having to ask us.

You can also just delete this code u commented out if it's somewhere else

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Looks really good 🔥🔥🔥

File: src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx [hunk 3]
```diff
@@ -144,7 +166,13 @@ const WorkPackageFormView: React.FC<WorkPackageFormViewProps> = ({
...
   };
 
-  const crIdDisplay = crId ?? defaultValues?.crId;
+  const showChangeRequestModal = () => {
+    setIsModalOpen(true);
+  };
+
+  const crWatch = useWatch({ control, name: 'crId' });
+
+  console.log(crWatch);
```
Comment (walker-sean) [inline src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx:175]: Remove this

**Review by walker-sean — CHANGES_REQUESTED** [review]

**Review by walker-sean — APPROVED** [review]
