### PR TITLE
#1554 form validation fix for crID for project/wp edit

### LINKED ISSUE #1554: Form Validation not working for crID for WP/Project edit
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

production (main)

### Observed Behavior

Right now the work packages and project edits forms don't display a form error if the crId field isn't filled out, instead it tries to submit the payload to the backend and displays an http error from there.

### Expected Behavior

If you don't have the crId filled out on the work package/ project edit forms it should display an error msg under the input when you try to submit and not let you submit the form

### Steps to Reproduce

1. Try to edit a project/wp with no crId set

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by jessicayzhao**
## Changes

Added an error message if crID isn't filled out on the work package/ project edit forms.

## Screenshots
Screenshot 2023-10-11 at 8 55 47 PM
Screenshot 2023-10-11 at 8 55 52 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1554

### CODE REVIEW

File: src/frontend/src/components/ChangeRequestDropdown.tsx [hunk 1]
```diff
@@ -33,9 +33,11 @@ const getFilteredChangeRequests = (changeRequests: ChangeRequest[], user: Authen
 interface ChangeRequestDropdownProps {
   control: Control<any, any>;
   name: string;
+  errors: FieldErrors<ChangeRequest>;
+  errorMessage?: FieldError;
```
Comment (callmejim1226) [inline src/frontend/src/components/ChangeRequestDropdown.tsx:37]: We wanna minimize the number of inputs/arguments in the component as much as we can. We can delete `errorMessage` field, and replace `errorMessage` with `errors.crId` on line 69 in this file.

File: src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx [hunk 2]
```diff
@@ -174,7 +180,7 @@ const ProjectEditContainer: React.FC<ProjectEditContainerProps> = ({ project, ex
     <PageLayout
       title={`${wbsPipe(project.wbsNum)} - ${project.name}`}
       previousPages={[{ name: 'Projects', route: routes.PROJECTS }]}
-      headerRight={<ChangeRequestDropdown control={control} name="crId" />}
+      headerRight={<ChangeRequestDropdown control={control} name="crId" errors={errors} errorMessage={errors.crId} />}
```
Comment (callmejim1226) [inline src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx:183]: We want to update this line after resolving my comment in `ChangeRequestDropdown` file.

**Review by callmejim1226 — CHANGES_REQUESTED** [review]
Great work!

Left a comment on `ChangeRequetDropdown` component's inputs.

File: src/frontend/src/components/ChangeRequestDropdown.tsx (hunk 1 above)
Comment (callmejim1226) [inline src/frontend/src/components/ChangeRequestDropdown.tsx:37]: We can also delete the `errorMessage?` property here since we're not passing this property in anywhere in the codebase.

**Review by callmejim1226 — CHANGES_REQUESTED** [review]
Great work! I just left a minor comment, and it should be good for the final review! 

Also, don't forget to put a checkmark on all PR checklists, update the PR labels, and click `Resolve conversation` on my resolved comments.

**Review by callmejim1226 — APPROVED** [review]
LGTM! I was able to see the error message under the CRID field when I tried to edit the project/work package without filling crID.
