### PR TITLE
#1020 Fix Permissions and Toast Display

### LINKED ISSUE #1020: Fix Create Task Perms
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop

### Version(s)

production (main), develop

### Observed Behavior

Project leads cant make tasks

### Expected Behavior

should be able to 

### Steps to Reproduce

1. create proj with a member lead
2. try to create task
3. button is disabled

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

Fixed Task Perms and Weird toast display that displayed success no matter what. 

## Screenshots
Screen Shot 2023-03-21 at 1 11 59 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1020 (issue #)

### CODE REVIEW

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx [hunk 1]
```diff
@@ -38,12 +38,13 @@ const TaskList = ({ project, defaultClosed }: TaskListProps) => {
   if (!user) return <LoadingIndicator />;
 
   const createTaskPermissions =
-    !(user.role === 'GUEST' && !project.team?.members.map((user) => user.userId).includes(user.userId)) &&
-    !(
-      user.role === 'MEMBER' &&
-      (project.projectLead?.userId !== user.userId || project.projectManager?.userId !== user.userId) &&
-      !(project.team?.leader.userId === user.userId)
-    );
+    user &&
```
Comment (RChandler234) [inline src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx:41]: Don't think you need this since we have the loading indicator thing above

**Review by RChandler234 — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx (hunk 1 above)
Comment (Peyton-McKee) [reply src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx:41]: u right

**Review by anthonybernardi — APPROVED** [review]
