### PR TITLE
#509 - fix mui column filtering as temp solution

### LINKED ISSUE #509: General - Fix Bad MUI Data Grid Stuff
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop, iOS, Android

### Version(s)

main, production

### Observed Behavior

Column data types are not set up properly. WBS would be better done flattened and combined. Blah blah blah.

### Expected Behavior

Make filters work

### Steps to Reproduce

1. Look at prod
2. Try to filter
3. Ew

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by jamescd18**
## Changes

Created good enough temp solution for fixing all the column filtering. Flatten some data into types that MUI can handle, add type specification for columns, and disable filtering on columns that are simply too complex.

## Notes

Pair programmed with Peyton! We dug into figuring out how MUI Data Grids work and decided that this temp solution would be best to get features working for users. I think that at some future point it would be awesome to investigate creating custom filter operators for the more complex data types (WBS Numbers, Users, etc.) as well as adding the quick filter in with custom quick filter functions for columns. Both those are noted in #505.

## Test Cases

Lol none.

## Screenshots

Screenshot 2022-12-24 at 11 37 35 PM

Screenshot 2022-12-24 at 11 37 58 PM

## To Do

n/a

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #509

### CODE REVIEW

File: src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx [hunk 1]
```diff
@@ -152,7 +161,15 @@ const ChangeRequestsTable: React.FC = () => {
...
         error={error}
-        rows={data || []}
+        rows={
+          // flatten some complex data to allow MUI to sort/filter yet preserve the original data being available to the front-end
+          data?.map((v) => ({
+            ...v,
+            carNumber: v.wbsNum.carNumber,
+            submitter: fullNamePipe(v.submitter),
+            reviewer: fullNamePipe(v.reviewer)
+          })) || []
```
Comment (RChandler234) [inline src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx:171]: what's the benefit of doing it this way instead of using the valueFormatter?

Comment (jamescd18) [reply src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx:171]: OK so there's big problems with using value formatter. Value for matter, preserves movies, handling of the original data type, an object when a user input six string to filter the column, movie compares the string to the original type, an object. We have yet to figure out how to properly get the input string to be properly compared to the original object people saw so instead, we are just going to flatten the data before it gets to MUI, but after it comes in from the API. Does provides the most amount of flexibility and fixes the problem in the easiest way possible

**Review by RChandler234 — APPROVED** [review]
