### PR TITLE
#310 adjusted the crId field in project edits to be empty instead of -1

### LINKED ISSUE #310: Frontend - Project Edit Page Default crId is -1
### Browser(s)

_No response_

### Platform(s)

_No response_

### Version(s)

_No response_

### Observed Behavior

When you click edit on the project page, it autofills the crId field to -1. This is because I did some query params stuff on the page. It doesn't show up on the work package edit page though because the two pages are a little different in how they treat it. I think one views it as a string and another as a number.

### Expected Behavior

it should be empty

### Steps to Reproduce

1. click edit on any project

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by ethankong150**
## Changes

changed the default project edit crID field to be empty instead of -1

## Notes

n/a

## Test Cases

check if the field can't be negative
check if the field remains empty when refreshing
check that a value has to be manually added to the field

## Screenshots

Screenshot (122)
Screenshot (124)

Screenshot (123)
Screenshot (125)

## To Do

nah we chillin

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #310

### CODE REVIEW

**Review by Ari-S-123 — APPROVED** [review]

File: src/frontend/src/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ const ProjectEditContainer: React.FC<ProjectEditContainerProps> = ({ proj, exitE
   const allUsers = useAllUsers();
   const { mutateAsync } = useEditSingleProject(proj.wbsNum);
 
-  const [crId, setCrId] = useState(query.get('crId') || -1);
+  const [crId, setCrId] = useState(query.get('crId') || NaN);
```
Comment (anthonybernardi) [inline src/frontend/src/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.tsx:48]: not a fan of `NaN`, you can just do empty string then you'll have to change one line below

**Review by anthonybernardi — CHANGES_REQUESTED** [review]

**Review by anthonybernardi — APPROVED** [review]
awesome!
