### PR TITLE
#961 fix logout button

### LINKED ISSUE #961: Fix Logout Button on Prod
logout is still broken, we need to fix it fast

we should probs use the qa environment to test it so talk to me about that

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

So when we moved the menu item inside of the google logout, we forgot to add the onclick={renderProps.onclick) function, so we never actually called the google logout button. Now we do and it works (i dont think trickster mode works on dev but does that really matter?)

## Screenshots
Screen Shot 2023-03-05 at 4 59 58 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #961 (issue #)

### CODE REVIEW

File: src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx [hunk 1]
```diff
@@ -36,11 +36,11 @@ const NavUserMenu: React.FC = () => {
 
   const ProdLogout = () => (
     <GoogleLogout
-      clientId={googleAuthClientId!}
+      clientId={process.env.REACT_APP_GOOGLE_AUTH_CLIENT_ID!}
```
Comment (anthonybernardi) [inline src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx:39]: y change

File: src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx [hunk 2]
```diff
@@ -115,7 +115,7 @@ const NavUserMenu: React.FC = () => {
           <ListItemText>Settings</ListItemText>
         </MenuItem>
         {auth.user?.role === 'ADMIN' || auth.user?.role === 'APP_ADMIN' ? <AdminTools /> : null}
-        {process.env.NODE_ENV === 'development' ? <DevLogout /> : <ProdLogout />}
```
Comment (anthonybernardi) [inline src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx:118]: can u go back to the development one because otherwise local logout doesnt work for me for some reason

File: src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx [hunk 3]
```diff
@@ -125,6 +125,7 @@ const ProjectEditContainer: React.FC<ProjectEditContainerProps> = ({ project, ex
     };
 
     try {
+      console.log('test');
```
Comment (anthonybernardi) [inline src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx:128]: delete

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
bless

File: src/frontend/src/pages/SettingsPage/Settings.tsx [hunk 4]
```diff
@@ -80,15 +81,15 @@ const Settings: React.FC = () => {
...
-                    onClick={() => {
+                  <GoogleLogout
+                    clientId={process.env.REACT_APP_GOOGLE_CLIENT_ID || ''}
+                    onLogoutSuccess={() => {
                       setShowAlert(true);
                       setTimeout(() => {
                         auth.signout();
                       }, 2000);
                     }}
+                    render={(renderProps) => <NERSwitch id="trick-switch" sx={{ m: 1 }} onClick={renderProps.onClick} />}
```
Comment (RChandler234) [inline src/frontend/src/pages/SettingsPage/Settings.tsx:92]: trickster mode is not signing me out

Comment (RChandler234) [reply src/frontend/src/pages/SettingsPage/Settings.tsx:92]: looks like it's a cors error or something in the console

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Review by RChandler234 — APPROVED** [review]

**Review by anthonybernardi — APPROVED** [review]
