### PR TITLE
#98 backend errors 4xx

### LINKED ISSUE #98: Projects - Endpoints Should Use `res.status(40X).json({ message: 'x' })` Not `throw new TypeError()`
## Description

Specifying errors on the 4xx level instead of 5xx would allow for project managers to independently troubleshoot any usage errors, omitting unnecessary follow-up with the software team.

## Background

Currently, the implementation of `throw new TypeError()` returns only 500 internal server error responses, which provides minimal feedback to users on what went wrong. Instead we should use express res to send a useful status and message

## Desired Behavior

4xx level errors should be returned.

## Proposed Solution

The `res.status(40X).json({message: 'blah blah blah'})` function should be implemented instead of `throw new TypeError()`, enabling error messages to be sent back to the front-end and be properly handled. Some reading material [here](https://www.tutorialspoint.com/session_initiation_protocol/sip_client_failure_responses.htm).

## Problem Areas

NOTE: These are outdated and from v2

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/1062a1dc92e156db5141b1df4a57530d4b3446f5/src/backend/functions/work-packages.ts#L71

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/1062a1dc92e156db5141b1df4a57530d4b3446f5/src/backend/functions/projects.ts#L106

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/1062a1dc92e156db5141b1df4a57530d4b3446f5/src/backend/functions/users.ts#L25

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/1062a1dc92e156db5141b1df4a57530d4b3446f5/src/backend/functions/work-packages-create.ts#L41

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/1062a1dc92e156db5141b1df4a57530d4b3446f5/src/backend/functions/work-packages.ts#L71

### PR DESCRIPTION
**Pull request by sho-r1024**
## Changes

We added some tests to the work-packages.test.ts file, mainly tests with checking for a valid WBS Element ID and tests checking for null dependencies.

Other changes included: 

in wp controller : `throw TypeError` replaced with `return res.status(400)`
in `userTransformer`, `projectTransformer`, `teamTransformer`:  `TypeError` check for null input removed because TypeScript enforces that the input cannot be null

## To Do

Not sure if there's much else to do, but we'd like to double check before finalizing everything.

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors
- [x] No newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (if applicable)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] PR is linked to the ticket
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack

Closes #98

### CODE REVIEW

File: src/backend/src/controllers/work-packages.controllers.ts [hunk 1]
```diff
@@ -101,10 +101,16 @@ export const createWorkPackage = async (req: Request, res: Response) => {
   // and what number work package this should be
   const { carNumber, projectNumber, workPackageNumber } = projectWbsNum;
 
-  if (workPackageNumber !== 0) throw new TypeError('Given WBS Number is not for a project.');
+  if (workPackageNumber !== 0) {
+    return res
+      .status(400)
+      .json({ message: `Given WBS Number ${projectWbsNum.toString()} is not for a project.` });
```
Comment (anthonybernardi) [inline src/backend/src/controllers/work-packages.controllers.ts:107]: this will just print `Given WbS Number [object Object] is not for a project.` -- instead do something like `Given WBS Number ${carNumber}.${projectNumber} ...` blah blah blah etc yk

File: src/backend/src/controllers/work-packages.controllers.ts [hunk 2]
```diff
@@ -156,12 +162,16 @@ export const createWorkPackage = async (req: Request, res: Response) => {
...
 
-  const dependenciesIds = dependenciesWBSElems.map((elem) => {
-    if (elem === null) throw new TypeError('One of the dependencies was not found.');
-    return elem.wbsElementId;
+  const dependenciesIds: number[] = [];
+  // populate dependenciesIds with the element ID's
+  // and return error 400 if any elems are null
+  dependenciesWBSElems.forEach((elem) => {
+    if (elem === null) {
+      return res.status(400).json({ message: 'One of the dependencies was not found.' });
```
Comment (anthonybernardi) [inline src/backend/src/controllers/work-packages.controllers.ts:170]: this won't work because returning inside a forEach just ends the foreach and doesn't actually return from the outer function. set up a boolean outside like `dependenciesHasNulls` or something then after the forEach if it's true then you return the res 400

File: src/backend/tests/work-packages.test.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
+import request from 'supertest';
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:1]: there is already a tests folder and a work-packages.test.ts file one directory above this

File: src/backend/tests/work-packages.test.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+  deliverables: [{ descriptionId: 3, dateAdded: '01/01/22', detail: 'did it work' }]
+};
+
+describe('Work Packages', () => {
+  beforeEach(() => {
+    prisma.work_Package.findMany = jest.fn();
+    prisma.work_Package.findUnique = jest.fn();
+  });
+
+  test('createWorkPackage fails if WBS number does not represent a project', async () => {
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:41]: you need to mock every prisma call that happens before the call to the endpoint finishes. For both of these, that means mocking `prisma.user.findUnique` and `prisma.change_Request.findUnique`. see the existing test files for how to do that

**Review by anthonybernardi — CHANGES_REQUESTED** [review]

File: src/backend/src/controllers/work-packages.controllers.ts (hunk 2 above)
Comment (sho-r1024) [reply src/backend/src/controllers/work-packages.controllers.ts:170]: Why would we want to run the entire foreach loop if there's a null?

Comment (anthonybernardi) [reply src/backend/src/controllers/work-packages.controllers.ts:170]: you're right, what I'm saying is that returning inside a foreach only ends the foreach (it's like `break`). the outer endpoint will keep running after that. You should end early if you see a null, but you also need a way to make sure the outer endpoint finishes too if you do that

File: src/backend/tests/work-packages.test.ts (hunk 3 above)
Comment (sho-r1024) [reply src/backend/tests/work-packages.test.ts:1]: Where would I find the other tests folder? I can only seem to find one on my end

Comment (anthonybernardi) [reply src/backend/tests/work-packages.test.ts:1]: one directory above this. backend/tests

File: src/backend/tests/work-packages.test.ts (hunk 4 above)
Comment (sho-r1024) [reply src/backend/tests/work-packages.test.ts:41]: Do we have to mock for prisma.work_Package.findUnique and prisma.work_Package.findAll? Also, would prisma.user.findUnique and prisma.change_Request.findUnique basically involve creating a user and creating a change request and then running jest.SpyOn() on both of them?

Comment (anthonybernardi) [reply src/backend/tests/work-packages.test.ts:41]: 1. in this case no you don't have to mock those because if the code is working as intended then the endpoint will fail before it even gets to those (returning the 400)
2. yeah pretty much. you can copy how that's done in the other files. it's kinda work intensive though so we should definitely in the future find a way to make it easier (probably by using pre made sample data that we can just import)

Comment (sho-r1024) [reply src/backend/tests/work-packages.test.ts:41]: @anthonybernardi Do I just test whether the two methods are called or is there more I have to do?

Comment (anthonybernardi) [reply src/backend/tests/work-packages.test.ts:41]: what two methods? the title of the test is what you're testing. For example, if you pass in 1 for work package number, it should fail right. That's already the case, we're just mocking any prisma calls along the way so that we aren't relying on prisma being in any certain state.

Comment (sho-r1024) [reply src/backend/tests/work-packages.test.ts:41]: `prisma.user.findUnique` and `prisma.change_Request.findUnique` are the two methods, how would I make the mock to test it? ig I'm just kinda confused about how the mocks in the other test files work?

File: src/backend/tests/work-packages.test.ts [hunk 5]
```diff
@@ -0,0 +1,154 @@
+import request from 'supertest';
+import express from 'express';
+import workPackageRouter from '../src/routes/work-packages.routes';
+import { CR_Type, Role, WBS_Element_Status } from '@prisma/client';
+import prisma from '../src/prisma/prisma';
+import { WbsElement } from 'shared';
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:6]: unused, delete the line

File: src/backend/tests/work-packages.test.ts [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+const batman = {
+  userId: 1,
+  firstName: 'Bruce',
+  lastName: 'Wayne',
+  email: 'notbatman@gmail.com',
+  emailId: 'notbatman',
+  role: Role.APP_ADMIN
+};
+
+const nullReturn = () => {
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:23]: unused, delete the function

File: src/backend/tests/work-packages.test.ts [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+import workPackageRouter from '../src/routes/work-packages.routes';
+import { CR_Type, Role, WBS_Element_Status } from '@prisma/client';
+import prisma from '../src/prisma/prisma';
+import { WbsElement } from 'shared';
+
+const app = express();
+app.use(express.json());
+app.use('/', workPackageRouter);
+
+jest.mock('../src/utils/work-packages.utils');
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:12]: i don't think this is used anywhere

File: src/backend/tests/work-packages.test.ts [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+    jest.spyOn(prisma.wBS_Element, 'findUnique').mockResolvedValueOnce(someWBElement);
+    jest.spyOn(prisma.wBS_Element, 'findUnique').mockResolvedValueOnce(null);
+
+    const res = await request(app).post('/create').send(createWorkPackagePayload);
+
+    expect(res.statusCode).toBe(400);
+    expect(res.body.message).toBe('One of the dependencies was not found.');
+  });
+
+  test('findUniqueUser', async () => {
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:144]: delete this entire test

File: src/backend/tests/work-packages.test.ts [hunk 9]
```diff
@@ -0,0 +1,154 @@
...
+      }
+    };
+    const res = await request(app).post('/create').send(proj);
+
+    expect(res.statusCode).toBe(400);
+    expect(res.body.message).toBe('Given WBS Number 1.2.2 is not for a project.');
+  });
+
+  test('createWorkPackage fails if any elements in the dependencies are null', async () => {
+    jest.spyOn(prisma.user, 'findUnique').mockResolvedValue({ ...batman, googleAuthId: 'b' });
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:133]: no reason to change the google auth id right? you can just mock the resolved value to be batman

File: src/backend/tests/work-packages.test.ts [hunk 10]
```diff
@@ -0,0 +1,154 @@
...
+describe('Work Packages', () => {
+  beforeEach(() => {
+    prisma.user.findUnique = jest.fn();
+    prisma.change_Request.findUnique = jest.fn();
+    prisma.work_Package.findMany = jest.fn();
+    prisma.work_Package.findUnique = jest.fn();
+  });
+
+  test('createWorkPackage fails if WBS number does not represent a project', async () => {
+    jest.spyOn(prisma.user, 'findUnique').mockResolvedValue({ ...batman, googleAuthId: 'b' });
```
Comment (anthonybernardi) [inline src/backend/tests/work-packages.test.ts:116]: same thing as my other comment

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
nice nice. After making my requested changes, see if the checks pass. this time the checks failed because the mocks weren't fully done so it tried to call prisma (but the github checks aren't hooked up to prisma so it fails). If it still fails (or the test check takes > 5 minutes) then that means you missed something to mock

File: src/backend/tests/work-packages.test.ts (hunk 9 above)
Comment (sho-r1024) [reply src/backend/tests/work-packages.test.ts:133]: unfortunately TS throws an error saying "googleauthid is missing", not sure why

**Review by anthonybernardi — APPROVED** [review]
nice!
