### PR TITLE
#1036 - roger huang - wp stage chip misaligned fix

### LINKED ISSUE #1036: Frontend - WP Stage Chip is Misaligned
### Browser(s)

_No response_

### Platform(s)

_No response_

### Version(s)

_No response_

### Observed Behavior

the wp stage chip is in the middle of the page block

### Expected Behavior

it should be on the far right just to the left of the active chip

### Steps to Reproduce

1. give a wp a stage
2. look at the chip being weird

### Screenshots (as needed)

Screenshot 2023-03-22 at 11 29 21 PM

### PR DESCRIPTION
**Pull request by rhuang772**
## Changes

I fixed the work package stage chip alignment so that both WbsStatus and itself appear right next to each other instead of with a giant space in between.

## Screenshots
image

image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1036

### CODE REVIEW

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx [hunk 1]
```diff
@@ -15,15 +15,19 @@ interface WorkPackageDetailsProps {
   workPackage: WorkPackage;
 }
 
+// {workPackage.stage ? <WorkPackageStageChip stage={workPackage.stage}  /> : null}
```
Comment (anthonybernardi) [inline src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:18]: delete pls

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
nice! dont forget to tag commits with issue number

File: src/frontend/src/components/WorkPackageStageChip.tsx [hunk 2]
```diff
@@ -41,7 +41,7 @@ const WorkPackageStageChip: React.FC<WorkPackageStageChipProps> = ({ stage }) =>
         variant="outlined"
         sx={{
           fontSize: 14,
-          mr: '5px',
+          mr: '0px',
```
Comment (anthonybernardi) [inline src/frontend/src/components/WorkPackageStageChip.tsx:44]: i think this should be 5px still because if you go to like http://localhost:3000/projects/1.1.0 the two chips are touching in the work package section

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
nice! just one more thing

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx [hunk 3]
```diff
@@ -20,10 +20,12 @@ const WorkPackageDetails: React.FC<WorkPackageDetailsProps> = ({ workPackage })
     <PageBlock
       title={'Work Package Details'}
       headerRight={
-        <>
-          {workPackage.stage ? <WorkPackageStageChip stage={workPackage.stage} /> : null}
+        <div style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center' }}>
```
Comment (nezamj03) [inline src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: I would be consistent with the rest of codebase by using primarily Grid tags here. You can create a similar design without using style, display, or align items.

Instead, by using a grid and justifying content right

**Review by nezamj03 — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx [hunk 4]
```diff
@@ -20,10 +20,14 @@ const WorkPackageDetails: React.FC<WorkPackageDetailsProps> = ({ workPackage })
     <PageBlock
       title={'Work Package Details'}
       headerRight={
-        <>
-          {workPackage.stage ? <WorkPackageStageChip stage={workPackage.stage} /> : null}
-          <WbsStatus status={workPackage.status} />
-        </>
+        <Grid container alignItems="center" justifyContent="flex-end">
```
Comment (nezamj03) [inline src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: I would try and yarn start this to see what it looks like -- it doesnt look great as the container messes with the way everything looks because it claims to take full width.

So, the way I would approach this is as follows: 

I looked through the codebase and some Grid documentation and its generally not great for this because the way our headerRight works doesn't supplement a container Grid component. Instead, I would use something like a div -- a Box. Generally, we want all our components to be Material UI, and that is why we dont use div, span, etc...

In Material UI, a Box component is like a (essentially) more customizable, better <div>. So, I would make _one_ Box component with the stage chip and the status inside of it, and in justify the content of the Box to the right. Let me know if you have any questions.

Comment (nezamj03) [reply src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: Generally, it's important you yarn start and checking how it looks before a PR. As you can see the "Work Package Details" gets misformatted with the container. 

Screen Shot 2023-04-03 at 1 24 24 PM

**Review by nezamj03 — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx [hunk 5]
```diff
@@ -20,10 +20,10 @@ const WorkPackageDetails: React.FC<WorkPackageDetailsProps> = ({ workPackage })
     <PageBlock
       title={'Work Package Details'}
       headerRight={
-        <>
+        <Box display="flex" justifyContent="flex-end">
```
Comment (nezamj03) [inline src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: last super small thing - because headerRight is formatter to already format them to the right, you can delete display="flex" justifyContent="flex-end"

**Review by nezamj03 — CHANGES_REQUESTED** [review]

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx (hunk 5 above)
Comment (rhuang772) [reply src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: got it!

File: src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx [hunk 6]
```diff
@@ -20,10 +20,10 @@ const WorkPackageDetails: React.FC<WorkPackageDetailsProps> = ({ workPackage })
     <PageBlock
       title={'Work Package Details'}
       headerRight={
-        <>
+        <Box>
```
Comment (nezamj03) [inline src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx:23]: nice!

**Review by nezamj03 — APPROVED** [review]
lgtm!

**Review by anthonybernardi — APPROVED** [review]
nice! looks good
