### PR TITLE
#3997 fixed project budget + updated rr seed data

### LINKED ISSUE #3997: [Maintenance] - Budget Fix RRs split between projects
### Description
Reimbursement requests can be split between multiple projects. In the budget section of project details, it should only have the value given for that specific project, not the total value of the reimbursement request. 

For example, if I create a reimbursement request with only 20 dollars allocated from the stadium budget, it shouldn't show the full 35 dollars here. It should also only take away 20 dollars from the overall budget calculation up top.

Image

### Screenshots
Original example:  $1389 total reimbursement request amount, but this project should only be for $189

Image

### PR DESCRIPTION
**Pull request by cielbellerose**
## Changes

Updates the project budget page to use the costs associated only with this project for the budget calculations. Also includes a column, in addition to the total cost column, for the $ in the rr associated with this project

- also fixed rr seed data bc totalCost is assumed to be in cents

## Screenshots

Screenshot 2026-03-15 at 7 05 27 PM
---
Screenshot 2026-03-15 at 7 11 21 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #3997

### CODE REVIEW

File: src/frontend/src/pages/ProjectPage/ProjectSpendingHistory.tsx [hunk 1]
```diff
@@ -128,7 +75,81 @@ const ProjectSpendingHistory: React.FC<ProjectSpendingHistoryProps> = ({ wbsNum
       budgetRemaining,
       budgetUsedPercentage
     };
-  }, [project, reimbursementRequests]);
+  }, [project, reimbursementRequests, wbsNum]);
+
+  const columns: GridColDef[] = [
```
Comment (cielbellerose) [inline src/frontend/src/pages/ProjectPage/ProjectSpendingHistory.tsx:80]: the columns are all the same except the projectCost addition, just had to move them inside to use the wbsNum

**Review by chpy04 — APPROVED** [review]
lit
