### PR TITLE
#496 Remove href and use External Links and React Router Dom

### LINKED ISSUE #496: Teams - Links Are Non-Functional Redirecting to Login
### Browser(s)

Safari

### Platform(s)

Desktop, iOS

### Version(s)

main, production

### Observed Behavior

Clicking on links on the teams page redirects to the login page. On safari this prevents using the links at all and navigates to the home page.

### Expected Behavior

The links should directly navigate to the linked page.

### Steps to Reproduce

1. Open finish line in Safari
2. Navigate to the Teams page
3. Click on a button to view a team or a link to view a project
4. Find yourself at the home page after a brief view of the login page

On Chrome and Firefox:
1. Navigate to the Teams page
2. Click to view a team or to view a project
3. Briefly view the login page as you get logged in again
4. Find yourself at the correct page

### Screenshots (as needed)

Proper use of Link that does not show this behavior:
Screenshot 2022-12-16 at 3 42 47 PM
Screenshot 2022-12-16 at 3 43 10 PM

Use of link in the teams page:
Screenshot 2022-12-16 at 3 43 38 PM
a985-8951-4393-a994-5e48a4d5dcec.png">
Screenshot 2022-12-16 at 3 43 26 PM

### PR DESCRIPTION
**Pull request by Peyton-McKee**
## Changes

Removed all possible instances of href to use either internal react router or the ExternalLinks component.

## Notes

tests are failing, I don’t know why, mostly because I don’t know about front end tests the new linkings work though.

## ScreenshotS
User settings changed to a div with flex display for using external links

Screen Shot 2022-12-18 at 6 57 59 PM

Screen Shot 2022-12-18 at 6 57 47 PM

Screen Shot 2022-12-18 at 6 58 16 PM

Screen Shot 2022-12-18 at 6 58 07 PM

Change Request Page:

Screen Shot 2022-12-20 at 6 06 19 PM

Screen Shot 2022-12-20 at 6 06 12 PM

Teams Page:

Screen Shot 2022-12-20 at 6 06 00 PM

Screen Shot 2022-12-20 at 6 05 52 PM

## To Do

fix tests ig

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ x] All commits are tagged with the ticket number
- [ x] No linting errors / newline at end of file warnings
- [x ] All code follows repository-configured prettier formatting
- [x ] No merge conflicts
- [ ] All checks passing
- [ x] Screenshots of UI changes (see Screenshots section)
- [ x] Remove any non-applicable sections of this template
- [ x] Assign the PR to yourself
- [ x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [ x] PR is linked to the ticket (fill in the closes line below)

Closes #496  (issue #)

### CODE REVIEW

File: src/frontend/src/pages/TeamsPage/TeamSummary.tsx [hunk 1]
```diff
@@ -35,8 +38,10 @@ const TeamSummary: React.FC<TeamSummaryProps> = ({ team }) => {
         </Typography>
       </CardContent>
       <CardActions>
-        <Button variant="outlined" size="small" component={Link} href={`${routes.TEAMS}/${team.teamId}`}>
-          See More
+        <Button variant="outlined" size="small">
```
Comment (Ari-S-123) [inline src/frontend/src/pages/TeamsPage/TeamSummary.tsx:41]: Can you change this to contained?

**Review by Ari-S-123 — CHANGES_REQUESTED** [review]
Can you post screenshots of the Change Request Detail Page and the Teams Page too?

File: src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx [hunk 2]
```diff
@@ -160,7 +160,9 @@ const ChangeRequestDetailsView: React.FC<ChangeRequestDetailsProps> = ({
             <Typography sx={{ fontWeight: 'bold' }}>WBS #: </Typography>
           </Grid>
           <Grid item xs={10}>
-            <MUILink href={`${routes.PROJECTS}/${wbsPipe(changeRequest.wbsNum)}`}>{wbsPipe(changeRequest.wbsNum)}</MUILink>
+            <MUILink component={Link} to={`${routes.PROJECTS}/${wbsPipe(changeRequest.wbsNum)}`}>
```
Comment (RChandler234) [inline src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx:163]: can you rename these while you're here so it's like the other ones: <Link component={RouterLink}

File: src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsEdit.tsx [hunk 3]
```diff
@@ -61,12 +62,13 @@ const UserSettingsEdit: React.FC<UserSettingsEditProps> = ({ currentSettings, on
...
-                <Link href="https://www.workast.com/help/article/how-to-find-a-slack-user-id/">
-                  (How to find your Slack ID)
-                </Link>
-              </Typography>
+              <Grid container>
+                <Typography>{'Slack Id '}</Typography>
+                <ExternalLink
+                  link="https://www.workast.com/help/article/how-to-find-a-slack-user-id/"
+                  description="(How to find your Slack ID)"
+                ></ExternalLink>
```
Comment (RChandler234) [inline src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsEdit.tsx:70]: this can be one tag: <ExternalLink props/>; also the way it's being used here, I'm thinking this should be a div with a style prop set to {display: 'flex'} instead of the grid component to get the same effect, since grid isn't really being used as a grid here

File: src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx [hunk 4]
```diff
@@ -13,10 +14,13 @@ interface UserSettingsViewProps {
...
-      <Link target="_blank" rel="noopener noreferrer" href={'https://nu-electric-racing.slack.com/team/' + settings.slackId}>
-        {settings.slackId}
-      </Link>
+      <Grid container>
+        <b>Slack ID: </b>
+        <ExternalLink
+          link={'https://nu-electric-racing.slack.com/team/' + settings.slackId}
+          description={settings.slackId}
+        ></ExternalLink>
+      </Grid>
```
Comment (RChandler234) [inline src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx:23]: same div comment and 1 tag comment as above

File: src/frontend/src/pages/TeamsPage/TeamSummary.tsx (hunk 1 above)
Comment (RChandler234) [reply src/frontend/src/pages/TeamsPage/TeamSummary.tsx:41]: I'd say just leave it alone for now tbh; when you switch it to contained, it makes the coloring messed up (it's red on red), might be good to bring up in another easy ticket for a new dev if we wanna change the look of this button, I know there's other stuff on this page that needs to be cleaned up looks-wise like that that's def out of scope for this ticket

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Comment by RChandler234** [comment]
Also not really sure what's up with the tests, I'll take another look at it tmrw and see if I have any luck

File: src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx [hunk 5]
```diff
@@ -3,20 +3,24 @@
...
-      <b>Slack ID: </b>
-      <Link target="_blank" rel="noopener noreferrer" href={'https://nu-electric-racing.slack.com/team/' + settings.slackId}>
-        {settings.slackId}
-      </Link>
+      <div style={style}>
+        <b>Slack ID: </b>
+        <ExternalLink
+          link={'https://nu-electric-racing.slack.com/team/' + settings.slackId}
+          description={settings.slackId}
+        ></ExternalLink>
```
Comment (RChandler234) [inline src/frontend/src/pages/SettingsPage/UserSettings/UserSettingsView.tsx:22]: For this External Link and the other one you use, because there aren't any child elements inside of them you can write them as `<ExternalLink link={} description={} />`, just a little cleaner

Also for the style prop you can do it this way or in cases like this where it's just one or two css prop you can do style ={{ display: 'flex', padding: 0 }} directly in the div. I'd reccomend doing it that way if there's only one css prop that's not likely to be changed later. It's good like this tho, just an fyi

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Review by RChandler234 — APPROVED** [review]

**Review by anthonybernardi — APPROVED** [review]
